#!/bin/bash

BASE_DIR=$(cd "`dirname $0`/../" && pwd)
SPEC_FILE="$BASE_DIR/cloud9.spec"
BUILD_DIR="/tmp/`basename $BASE_DIR`_build"

_name=`grep "^Name:" $SPEC_FILE | cut -d : -f 2 | tr -d ' '`

[ -d "$BUILD_DIR" ] && rm -rf $BUILD_DIR

mkdir -p $BUILD_DIR
cp $SPEC_FILE $BUILD_DIR

function fedora {
  [[ "$(cat /etc/redhat-release)" =~ "Fedora" ]] && return 0 || return 1
}

function rhel {
  [[ "$(cat /etc/redhat-release)" =~ "CentOS" ]] && return 0 || return 1
}

pushd $BASE_DIR > /dev/null
  if [ ! -d "node_modules" ]; then
    fedora && npm install --no-bin-links
    rhel && scl enable nodejs010 "npm install --no-bin-links"
  fi
  make packit

  tar -zcf $BUILD_DIR/node_modules.tar.gz node_modules
  tito build --test --tgz -o $BUILD_DIR
popd > /dev/null

SPEC_FILE="$BUILD_DIR/$(basename $SPEC_FILE)"
pushd $BUILD_DIR > /dev/null
  outfile=`ls ${_name}-*.tar.gz`
  commit=$(eval "echo $outfile | sed 's/^${_name}-//' | sed 's/\.tar\.gz$//' | tr - .")
  eval "sed -i -e 's/^Release:\(.*\)%{?dist}$/Release:\1.${commit}%{?dist}/' $SPEC_FILE"
  eval "sed -i -e 's/^Source0:.*$/Source0:${outfile}/' $SPEC_FILE"
  # remove .tar.gz
  outfile="${outfile%.*}"
  outfile="${outfile%.*}"
  eval "sed -i -e 's/^%setup.*$/%setup -q -n ${outfile}/' $SPEC_FILE"
  rpmbuild -ba $SPEC_FILE -D "_sourcedir $BUILD_DIR"
popd > /dev/null
