#!/bin/bash

BASE_DIR=$(cd "`dirname $0`/../" && pwd)
BUILD_DIR="`dirname $BASE_DIR`/`basename $BASE_DIR`_build"
mkdir -p $BUILD_DIR
cp $BASE_DIR/cloud9.spec $BUILD_DIR

pushd $BASE_DIR
  tito build --test --tgz
popd
